apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-pod-manager
  labels:
    app: fastapi
spec:
  replicas: 1  # Solo una instancia para manejar las conexiones
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: juanandresc/rosblocks-podmanager:latest  # Cambiar con la imagen real
        ports:
        - containerPort: 8000
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
